// Generated by delombok at Tue Sep 12 18:28:16 CEST 2023
package com.eternalcode.plots.database.warp;

import com.eternalcode.plots.plot.Plot;
import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import java.util.Date;
import java.util.UUID;

@DatabaseTable(tableName = "ep-plots")
public class PlotWarp {
    @DatabaseField(columnName = "plot_uuid", id = true)
    private UUID uuid;
    @DatabaseField(columnName = "plot_region", foreign = true, foreignAutoRefresh = true)
    private RegionWarp region;
    @DatabaseField(columnName = "plot_owner", foreign = true, foreignAutoRefresh = true)
    private MemberWarp owner;
    @DatabaseField(columnName = "plot_name")
    private String name;
    @DatabaseField(columnName = "plot_created")
    private Date created;
    @DatabaseField(columnName = "plot_expires")
    private Date expires;
    @ForeignCollectionField
    private ForeignCollection<FlagWarp> flags;
    @ForeignCollectionField
    private ForeignCollection<MemberWarp> members;

    private PlotWarp() {
    }

    private PlotWarp(UUID uuid, RegionWarp regionWarp, String name, Date created, Date expires) {
        this.uuid = uuid;
        this.region = regionWarp;
        this.name = name;
        this.created = created;
        this.expires = expires;
    }

    public static PlotWarp from(Plot plot) {
        PlotWarp plotWarp = new PlotWarp(plot.getUuid(), RegionWarp.from(plot.getRegion()), plot.getName(), plot.getCreated(), plot.getExpires());
        plotWarp.owner = MemberWarp.from(plotWarp, plot.getOwner());
        return plotWarp;
    }

    @java.lang.SuppressWarnings("all")
    public UUID getUuid() {
        return this.uuid;
    }

    @java.lang.SuppressWarnings("all")
    public RegionWarp getRegion() {
        return this.region;
    }

    @java.lang.SuppressWarnings("all")
    public MemberWarp getOwner() {
        return this.owner;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public Date getCreated() {
        return this.created;
    }

    @java.lang.SuppressWarnings("all")
    public Date getExpires() {
        return this.expires;
    }

    @java.lang.SuppressWarnings("all")
    public ForeignCollection<FlagWarp> getFlags() {
        return this.flags;
    }

    @java.lang.SuppressWarnings("all")
    public ForeignCollection<MemberWarp> getMembers() {
        return this.members;
    }
}
